// Generated by https://quicktype.io

export interface Auth {
  jwt:     string;
  details: null;
  user:    User;
}

export interface User {
  id:        number;
  username:  string;
  password:  string;
  email:     string;
  google:    boolean;
  isActive:  boolean;
  createdAt: string;
  roles:     Role[];
}

export interface Role {
  id:          number;
  name:        string;
  description: string;
  isActive:    boolean;
  createdAt:   string;
}