// Generated by https://quicktype.io

export interface ExerciseRecord {
  id:                 number;
  passenger:          Passenger;
  exercise:           Exercise;
  station:            string;
  duration:           number;
  challengeCompleted: boolean;
  createdAt:          string;
}

export interface Exercise {
  id:           number;
  exerciseType: string;
}

export interface Passenger {
  id:            number;
  firstName:     string;
  lastName:      string;
  email:         string;
  passengerType: string;
  createdAt:     null;
}
